name: Build Docker Image and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure Giriş
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Giriş
      uses: azure/docker-login@v1
      with:
        login-server: melikeacr01.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker Image Build ve Push
      run: |
        docker build . -t melikeacr01.azurecr.io/week11image:latest
        docker push melikeacr01.azurecr.io/week11image:latest

    - name: Azure Web App’e Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'melikewebappfr3' 
        images: 'melikeacr01.azurecr.io/week11image:latest'
